const routes = {
  post: {
    'api/user/admin-add': 'admin_add',
    'api/auth/admin-change-password': 'admin_change_password',
    'api/user/admin-change-status': 'admin_change_status',
    'api/user/admin-export': 'admin_export',
    'api/auth/admin-forgot-password': 'admin_forgot_password',
    'api/user/admin-list': 'admin_list',
    'api/auth/admin-login': 'admin_login',
    'api/auth/admin-logout': 'admin_logout',
    'api/auth/admin-reset-password': 'admin_reset_password',
    'api/auth/token-verification': 'admin_token_verification',
    'api/user/check-admin-email': 'check_admin_email',
    'api/user/check-customer-email': 'check_customer_email',
    'api/region/city-add': 'city_add',
    'api/region/city-change-status': 'city_change_status',
    'api/region/city-export': 'city_export',
    'api/region/city-list': 'city_list',
    'api/region/country-add': 'country_add',
    'api/region/country-change-status': 'country_change_status',
    'api/region/country-export': 'country_export',
    'api/region/country-list': 'country_list',
    'api/user/customer-add': 'customer_add',
    'api/auth/customer-change-password': 'customer_change_password',
    'api/user/customer-change-status': 'customer_change_status',
    'api/user/customer-export': 'customer_export',
    'api/auth/customer-forgot-password': 'customer_forgot_password',
    'api/user/customer-list': 'customer_list',
    'api/auth/customer-login': 'customer_login',
    'api/auth/customer-logout': 'customer_logout',
    'api/auth/customer-registration': 'customer_registration',
    'api/auth/customer-reset-password': 'customer_reset_password',
    'api/resources/email-templates-add': 'email_templates_add',
    'api/resources/email-templates-change-status':
      'email_templates_change_status',
    'api/resources/email-templates-export': 'email_templates_export',
    'api/resources/email-templates-list': 'email_templates_list',
    'api/resources/push-templates-add': 'push_templates_add',
    'api/resources/push-templates-change-status':
      'push_templates_change_status',
    'api/resources/push-templates-export': 'push_templates_export',
    'api/resources/push-templates-list': 'push_templates_list',
    'api/auth/resend-admin-verify-email': 'resend_admin_verify_email',
    'api/auth/resend-customer-verify-email': 'resend_customer_verify_email',
    'api/user/roles-add': 'roles_add',
    'api/user/roles-change-status': 'roles_change_status',
    'api/user/roles-export': 'roles_export',
    'api/user/roles-list': 'roles_list',
    'api/misc/save-draft': 'save_module_draft',
    'api/misc/search-criteria': 'search_criteria_add',
    'api/misc/search-criteria-update/:record_id': 'search_criteria_update',
    'api/tools/settings-upload-files': 'settings_upload_files',
    'api/resources/sms-templates-add': 'sms_templates_add',
    'api/resources/sms-templates-change-status': 'sms_templates_change_status',
    'api/resources/sms-templates-export': 'sms_templates_export',
    'api/resources/sms-templates-list': 'sms_templates_list',
    'api/region/state-add': 'state_add',
    'api/region/state-change-status': 'state_change_status',
    'api/region/state-export': 'state_export',
    'api/region/state-list': 'state_list',
    'api/resources/static-pages-add': 'static_pages_add',
    'api/resources/static-pages-change-status': 'static_pages_change_status',
    'api/resources/static-pages-export': 'static_pages_export',
    'api/resources/static-pages-list': 'static_pages_list',
    'api/user/customer-profile': 'update_customer_details',
    'api/user/profile-image': 'update_customer_profile_image',
    'api/auth/validate': 'validate_admin',
    'api/auth/verify-admin-email': 'verify_admin_email',
    'api/auth/verify-customer-email': 'verify_customer_email',
  },
  delete: {
    'api/user/admin-delete/:id': 'admin_delete',
    'api/region/city-delete/:id': 'city_delete',
    'api/region/country-delete/:id': 'country_delete',
    'api/user/customer-delete/:id': 'customer_delete',
    'api/resources/email-templates-delete/:id': 'email_templates_delete',
    'api/resources/push-templates-delete/:id': 'push_templates_delete',
    'api/user/roles-delete/:id': 'roles_delete',
    'api/misc/search-criteria-delete/:record_id': 'search_criteria_delete',
    'api/resources/sms-templates-delete/:id': 'sms_templates_delete',
    'api/region/state-delete/:id': 'state_delete',
    'api/resources/static-pages-delete/:id': 'static_pages_delete',
  },
  get: {
    'api/user/admin-details/:id': 'admin_details',
    'api/user/admin-dropdown-options': 'admin_dropdown_options',
    'api/user/identity': 'admin_identity',
    'api/auth/capabilities': 'capabilities',
    'api/region/city-details/:id': 'city_details',
    'api/region/city-dropdown-options': 'city_dropdown_options',
    'api/region/country-details/:id': 'country_details',
    'api/region/country-dropdown-options': 'country_dropdown_options',
    'api/user/customer-details/:id': 'customer_details',
    'api/user/customer-dropdown-options': 'customer_dropdown_options',
    'api/resources/email-templates-details/:id': 'email_templates_details',
    'api/resources/email-templates-dropdown-options':
      'email_templates_dropdown_options',
    'api/tools/general-settings': 'general_settings',
    'api/tools/dial-codes': 'get_country_dial_codes',
    'api/tools/countries': 'get_country_list',
    'api/user/customer-profile': 'get_customer_details',
    'api/misc/get-draft': 'get_module_draft',
    'api/tools/country-states': 'get_state_list',
    'api/tools/page/:page': 'get_static_page',
    'api/user/group-capability-list': 'group_capability_list',
    'api/auth/menu': 'menu',
    'api/resources/push-templates-details/:id': 'push_templates_details',
    'api/resources/push-templates-dropdown-options':
      'push_templates_dropdown_options',
    'api/user/roles-details/:id': 'roles_details',
    'api/user/roles-dropdown-options': 'roles_dropdown_options',
    'api/misc/search-criteria-list': 'search_criteria_list',
    'api/tools/settings': 'settings',
    'api/resources/sms-templates-details/:id': 'sms_templates_details',
    'api/resources/sms-templates-dropdown-options':
      'sms_templates_dropdown_options',
    'api/region/state-details/:id': 'state_details',
    'api/region/state-dropdown-options': 'state_dropdown_options',
    'api/resources/static-pages-details/:id': 'static_pages_details',
    'api/resources/static-pages-dropdown-options':
      'static_pages_dropdown_options',
  },
  put: {
    'api/user/admin-profile-update': 'admin_profile_update',
    'api/user/admin-update/:id': 'admin_update',
    'api/region/city-update/:id': 'city_update',
    'api/region/country-update/:id': 'country_update',
    'api/user/customer-update/:id': 'customer_update',
    'api/resources/email-templates-update/:id': 'email_templates_update',
    'api/user/group-capability-update/:id': 'group_capability_update',
    'api/resources/push-templates-update/:id': 'push_templates_update',
    'api/user/roles-update/:id': 'roles_update',
    'api/tools/settings-update': 'settings_update',
    'api/resources/sms-templates-update/:id': 'sms_templates_update',
    'api/region/state-update/:id': 'state_update',
    'api/resources/static-pages-update/:id': 'static_pages_update',
  },
};

export default routes;
